config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  namespace :api do
    post 'secret' => 'secret#create'
  end

end

app/models/occultis_label.rb
class OccultisLabel < ActiveRecord::Base
  attr_accessor :secure_message_label, :secure_iv_label, :secure_message_value, 
    :secure_iv_value

  belongs_to :user

  after_initialize do
    @encryptzator = Encryptzator.new  
  end

  def encrypt(label, value, pass)
    message_hash = perform(label, pass)
    self.secure_message_label = message_hash[:encrypted_message]
    self.secure_iv_label = message_hash[:iv]

    message_hash = perform(value, pass)
    self.secure_message_value = message_hash[:encrypted_message]
    self.secure_iv_value = message_hash[:iv]
    self.save
  end

  private

  def perform(abra, cadabra)
    @encryptzator.encrypt_message(abra, cadabra)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :occultis_labels
end

app/controllers/api/secret_controller.rb
class Api::SecretController < ApiController
  
  def create
    #binding.pry
    render nothing: true, status: 200, content_type:'text/html'    
  end

  private
  def valid_params
    params.require(:occultis_label).permit(:label, :value, :password)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_keys

  #check if key is supplied and check if it belongs to the current_user
  def check_keys
    binding.pry
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Welcome

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Memorygap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_header.html.haml
.navbar.navbar-inverse
  .container
    .navbar-header
      %a.navbar-brand.pull-left
        Memorygap
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a Home
        %li
          %a About
        %li
          -if user_signed_in?
            =link_to "Logout", destroy_user_session_path, method: :delete
          -else
            = form_for(:user, :url => session_path(:user)) do |f|
              = f.text_field :email
              = f.password_field :password 
              = f.submit 'Sign in'
              = link_to "Forgot your password?", new_password_path(:user)